login:
    path:     /login
    defaults: { _controller: LoginBundle:Default:login }
login_check:
    path:     /login_check
    defaults: { _controller: LoginBundle:Default:loginCheck }
logout:
    path:     /logout
    defaults: { _controller: LoginBundle:Default:logout }
